# Generated by Django 6.0.5 on 2026-05-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='analyst_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='co2e_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='normalized_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50),
        ),
    ]
